CREATE OR REPLACE FUNCTION SF_GET_LOANSTATUS(P_LOAN_AMNT NUMBER,
                                             P_COMD_NAME VARCHAR2)

 RETURN VARCHAR2 AS
  LN_ASSET NUMBER := 0;
BEGIN

  FOR I IN (SELECT ID.OFFER_DATE, ID.ASSET_AMNT, ID.FRACTION
              FROM INVENTORY_DTLS ID, MST_COMMODITY MC
             WHERE ID.COMD_ID = MC.COMD_ID
               AND MC.COMD_NAME = P_COMD_NAME
             ORDER BY ID.OFFER_DATE) LOOP
    IF I.FRACTION = 'Y' THEN
      LN_ASSET := LN_ASSET + I.ASSET_AMNT;
      IF LN_ASSET >= P_LOAN_AMNT THEN
        RETURN 'YES';
      END IF;
    END IF;
    IF I.FRACTION = 'N' THEN
      LN_ASSET := LN_ASSET + I.ASSET_AMNT;
      IF LN_ASSET >= P_LOAN_AMNT THEN
      
        IF LN_ASSET <= P_LOAN_AMNT THEN
          RETURN 'YES';
        END IF;
      END IF;
    END IF;
  
  END LOOP;
  RETURN 'NO';
END;
/
