CREATE OR REPLACE PROCEDURE SP_CANCEL_TRANSACTION (P_TRAN_ID NUMBER)

AS
CURSOR C1 IS SELECT TI.INV_ID,TI.INV_PAR_AMNT,TI.TRAN_ID,TI.STATUS FROM TRANS_INVEN_FRACTION TI WHERE 
TI.TRAN_ID = P_TRAN_ID;
LN_TRAN_ID TRANSACTION_SUMMARY.TRAN_ID%TYPE;
 BEGIN
   BEGIN
   SELECT TS.TRAN_ID INTO LN_TRAN_ID FROM TRANSACTION_SUMMARY TS WHERE TS.TRAN_ID = P_TRAN_ID AND TS.STATUS = 'P';
   EXCEPTION 
     WHEN NO_DATA_FOUND THEN
       RAISE_APPLICATION_ERROR(-20333,'YOU ENTERED AN INVALIED TRAN_ID');
       END;
   FOR I IN C1 LOOP
     IF I.STATUS = 'P' THEN
       
       UPDATE INVENTORY_DTLS ID SET ID.AVAL_AMNT = I.INV_PAR_AMNT+ID.AVAL_AMNT,ID.LOCK_AMNT= ID.LOCK_AMNT-I.INV_PAR_AMNT
       WHERE I.INV_ID = ID.INV_ID;
       END IF;
       END LOOP;
       UPDATE TRANSACTION_SUMMARY TS SET TS.STATUS ='X' WHERE TS.TRAN_ID =P_TRAN_ID;
       UPDATE TRANS_INVEN_FRACTION TI SET TI.STATUS ='X' WHERE TI.TRAN_ID = P_TRAN_ID;
       END ;
/
