CREATE OR REPLACE PROCEDURE SP_DAILY_INV_REPT
AS
CURSOR C1 IS SELECT INV_NAME , SUM(INV_COMM) INV_COMM FROM
(SELECT SF_GET_INV_NAME(TI.INV_ID) INV_NAME,(TI.INV_PAR_AMNT*TS.INV_COM_PER)/100 INV_COMM FROM  TRANS_INVEN_FRACTION TI,TRANSACTION_SUMMARY TS WHERE
 TI.TRAN_ID = TS.TRAN_ID AND TS.STATUS <> 'C') GROUP BY INV_NAME;
 EX EXCEPTION;
 PRAGMA EXCEPTION_INIT (EX,-1430);
 LV_ALTER VARCHAR2(1000);
 LV_UPDATE VARCHAR2(1000);
 
BEGIN
  INSERT INTO DAILY_INV_REPT (REPORT_DATE,VALUE) VALUES(SYSDATE,'INV COMM');
  FOR I IN C1 LOOP
    BEGIN
    LV_ALTER := 'ALTER TABLE DAILY_INV_REPT ADD '||I.INV_NAME|| ' NUMBER';
    EXECUTE IMMEDIATE LV_ALTER;
    LV_UPDATE := 'UPDATE DAILY_INV_REPT SET '||I.INV_NAME ||' = '||I.INV_COMM ||' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
    EXECUTE IMMEDIATE LV_UPDATE;
    EXCEPTION
      WHEN EX THEN
        LV_UPDATE := 'UPDATE DAILY_INV_REPT SET '||I.INV_NAME ||' = '||I.INV_COMM ||' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
    EXECUTE IMMEDIATE LV_UPDATE;
    END ;
    END LOOP;
    END;
/
