CREATE OR REPLACE PROCEDURE SP_DAILY_SUP_REPT
AS
CURSOR C1 IS SELECT SUP_NAME,SUM(SUP_COMM) COMM FROM (SELECT SF_SUP_NAME(SF_SUP_ID(TI.INV_ID)) SUP_NAME,TS.SUP_COM_PER,TI.INV_PAR_AMNT,(TI.INV_PAR_AMNT*TS.SUP_COM_PER)/100 SUP_COMM FROM
 TRANSACTION_SUMMARY TS,TRANS_INVEN_FRACTION TI WHERE TS.TRAN_ID = TI.TRAN_ID AND
 TRUNC(TS.TRAN_DATE)= TRUNC(SYSDATE) AND TS.STATUS <> 'C') GROUP BY SUP_NAME;
 EX EXCEPTION ;
 PRAGMA EXCEPTION_INIT(EX,-1430);
 FX EXCEPTION ;
 PRAGMA EXCEPTION_INIT(FX,-1430);
 LV_ALTER VARCHAR2(1000);
 LV_UPDATE VARCHAR2(1000);
 --LN_COUNT NUMBER;
 LV_UPDATEE VARCHAR2(1000);
 LV_SUPPLIERS VARCHAR2(1000);
 LV_QUERY VARCHAR2(2000):= 'SELECT REPORT_DATE,VALUE';
 LN_TOTAL_SUM INVENTORY_DTLS.ASSET_AMNT%TYPE:=0;
 BEGIN
    
   INSERT INTO DAILY_SUP_REPORT (REPORT_DATE,VALUE) VALUES (TRUNC(SYSDATE),'SUPPLIER COMM');
   FOR I IN C1 LOOP
      LN_TOTAL_SUM:= LN_TOTAL_SUM + I.COMM;

     LV_SUPPLIERS:=LV_SUPPLIERS||','||I.SUP_NAME;
     BEGIN
     LV_ALTER := 'ALTER TABLE DAILY_SUP_REPORT ADD '||I.SUP_NAME ||' NUMBER';
     EXECUTE IMMEDIATE LV_ALTER;
     LV_UPDATE := 'UPDATE DAILY_SUP_REPORT SET '||I.SUP_NAME ||' = '|| I.COMM ||
     ' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
     EXECUTE IMMEDIATE LV_UPDATE;
     EXCEPTION 
       WHEN EX THEN
          LV_UPDATE := 'UPDATE DAILY_SUP_REPORT SET '||I.SUP_NAME ||' = '|| I.COMM ||
     ' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
     EXECUTE IMMEDIATE LV_UPDATE;
     END;
     END LOOP;
     BEGIN
     LV_ALTER :=' ALTER TABLE DAILY_SUP_REPORT ADD  TOTAL_SUM NUMBER';
     EXECUTE IMMEDIATE LV_ALTER;
     LV_UPDATEE:= ' UPDATE DAILY_SUP_REPORT SET TOTAL_SUM = '||LN_TOTAL_SUM
      ||' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
 EXECUTE IMMEDIATE LV_UPDATEE;
     EXCEPTION 
       WHEN FX THEN
      LV_UPDATEE:= ' UPDATE DAILY_SUP_REPORT SET TOTAL_SUM = '||LN_TOTAL_SUM
      ||' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
 EXECUTE IMMEDIATE LV_UPDATEE;
     END;
     
     
     LV_QUERY :=LV_QUERY||LV_SUPPLIERS||','||'TOTAL_SUM'||' FROM DAILY_SUP_REPORT WHERE REPORT_DATE = '||CHR(39)||TO_CHAR(SYSDATE,'DD/MON/YYYY')||CHR(39);
      INSERT INTO QUERY_CRITERIA (REPORT_DATE,VALUE,QUERY) VALUES (TRUNC(SYSDATE),'SUP_COMM',LV_QUERY);
  
     END;
/
