CREATE OR REPLACE PROCEDURE SP_LOAN_ALGORITHM (P_LOAN_AMNT NUMBER,P_COMD_NAME VARCHAR2)
AS
LN_AVAL NUMBER:=0;
LN_LOCK NUMBER:=0;
LN_PAR_PER NUMBER;
LN_TRAN_PAR_PER NUMBER;
LV_STATUS VARCHAR2(100);
CURSOR C1 IS SELECT ID.INV_ID,ID.FRACTION,NVL(ID.AVAL_AMNT,ID.ASSET_AMNT) AVAL_AMNT FROM INVENTORY_DTLS ID,MST_COMMODITY MC WHERE 
ID.COMD_ID = MC.COMD_ID AND MC.COMD_NAME=P_COMD_NAME AND NVL(ID.LOCK_AMNT,0)<> ID.ASSET_AMNT ORDER BY ID.OFFER_DATE;
LN_LOAN_AMNT NUMBER :=P_LOAN_AMNT;
BEGIN
  LV_STATUS:=sf_get_loanstatus2(P_LOAN_AMNT,P_COMD_NAME);
  IF LV_STATUS = 'NO' THEN
    RAISE_APPLICATION_ERROR(-20333,'BANK DOES NOT HAVE THE MONEY TO GIVE LOAN');
    ELSIF LV_STATUS = 'YES' THEN
      INSERT INTO TRANSACTION_SUMMARY (TRAN_ID,TRAN_DATE,TRAN_AMNT,COMD_ID)
      VALUES (1,SYSDATE,P_LOAN_AMNT,sf_comd_id(P_COMD_NAME));   
   
    FOR I IN C1 LOOP
      IF LN_LOAN_AMNT > I.AVAL_AMNT THEN
        LN_AVAL:=LN_LOAN_AMNT - I.AVAL_AMNT;
        LN_LOCK :=ABS(I.AVAL_AMNT - LN_LOAN_AMNT);
        UPDATE INVENTORY_DTLS ID SET ID.AVAL_AMNT = 0,
        ID.LOCK_AMNT = NVL(ID.LOCK_AMNT,0)+LN_LOAN_AMNT WHERE ID.INV_ID = I.INV_ID;
        LN_PAR_PER:=I.AVAL_AMNT/P_LOAN_AMNT*100;
        LN_TRAN_PAR_PER := I.AVAL_AMNT /P_LOAN_AMNT *100;
        INSERT INTO TRANS_INVEN_FRACTION (INV_ID,INV_PAR_AMNT,COMD_ID,TRAN_ID,INV_PAR_PER,INV_TRAN_PAR_PER) 
        VALUES (I.INV_ID,LN_AVAL,sf_comd_id(P_COMD_NAME),1,LN_PAR_PER,LN_TRAN_PAR_PER);
        IF LN_LOAN_AMNT = 0 THEN
          EXIT;
          END IF;
        
        ELSIF LN_LOAN_AMNT < I.AVAL_AMNT AND I.FRACTION ='Y' THEN
           LN_AVAL:=I.AVAL_AMNT - LN_LOAN_AMNT;
           LN_LOCK :=ABS(I.AVAL_AMNT - LN_LOAN_AMNT);
           
           update INVENTORY_DTLS ID SET ID.AVAL_AMNT = I.AVAL_AMNT - LN_LOAN_AMNT, 
           ID.LOCK_AMNT = NVL(ID.LOCK_AMNT,0)+LN_LOAN_AMNT WHERE ID.INV_ID = I.INV_ID;
           LN_PAR_PER:=I.AVAL_AMNT/LN_LOAN_AMNT*100;
        LN_TRAN_PAR_PER := I.AVAL_AMNT /LN_LOAN_AMNT *100;
           INSERT INTO TRANS_INVEN_FRACTION (INV_ID,INV_PAR_AMNT,COMD_ID,TRAN_ID,INV_PAR_PER,INV_TRAN_PAR_PER)
           VALUES (I.INV_ID,LN_AVAL,sf_comd_id(P_COMD_NAME),1,LN_PAR_PER,LN_TRAN_PAR_PER);
           IF LN_LOAN_AMNT =0 THEN
             EXIT;
             END IF;
           ELSIF LN_LOAN_AMNT = I.AVAL_AMNT THEN
           --  LN_AVAL:=LN_LOAN_AMNT - I.AVAL_AMNT;
           -- LN_LOCK :=ABS(I.AVAL_AMNT - LN_LOAN_AMNT);
           UPDATE INVENTORY_DTLS ID SET ID.AVAL_AMNT = 0,ID.LOCK_AMNT = 
           NVL(ID.LOCK_AMNT,0)+LN_LOAN_AMNT WHERE ID.INV_ID = I.INV_ID;
            LN_PAR_PER:=I.AVAL_AMNT/LN_LOAN_AMNT*100;
        LN_TRAN_PAR_PER := I.AVAL_AMNT /LN_LOAN_AMNT *100;
        INSERT INTO TRANS_INVEN_FRACTION (INV_ID,INV_PAR_AMNT,COMD_ID,TRAN_ID,INV_PAR_PER,INV_TRAN_PAR_PER) VALUES
        (I.INV_ID,LN_LOAN_AMNT,sf_comd_id(P_COMD_NAME),1,LN_PAR_PER,LN_TRAN_PAR_PER);
        IF LN_LOAN_AMNT = 0 THEN
          EXIT;
          END IF;
        END IF;
        END LOOP;
        END IF;
        END;
           
/
