CREATE OR REPLACE PROCEDURE SP_OWN_REPT
AS
EX EXCEPTION ;
PRAGMA EXCEPTION_INIT(EX,-1430);
LV_ALTER VARCHAR2(1000);
LV_UPDATE VARCHAR2(1000);
LN_OWN_PER NUMBER;
BEGIN
  INSERT INTO DAILY_OWN_RPT (REPORT_DATE,VALUE) VALUES (TRUNC(SYSDATE),'OWN COMM'); 
  SELECT SUM((TI.INV_PAR_AMNT*TS.OWN_COM_PER)/100) OWN_PER INTO LN_OWN_PER FROM TRANSACTION_SUMMARY TS,TRANS_INVEN_FRACTION TI 
  WHERE TS.TRAN_ID = TI.TRAN_ID AND TS.STATUS <> 'C';
  BEGIN
    LV_ALTER:='ALTER TABLE DAILY_OWN_RPT ADD OWNER_COMM NUMBER';
    EXECUTE IMMEDIATE LV_ALTER;
    
    LV_UPDATE := 'UPDATE DAILY_OWN_RPT SET OWNER_COMM = '||LN_OWN_PER||' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
    EXECUTE IMMEDIATE LV_UPDATE;
    EXCEPTION 
      WHEN EX THEN
        LV_UPDATE := 'UPDATE DAILY_OWN_RPT SET OWNER_COMM = '||LN_OWN_PER||' WHERE TRUNC(REPORT_DATE) = TRUNC(SYSDATE)';
    EXECUTE IMMEDIATE LV_UPDATE;
    END ;
END;
/
