CREATE OR REPLACE PROCEDURE SP_SPLIT_INVENTORY (P_INV_ID NUMBER,P_INV_NAME VARCHAR2,P_SPLIT_PER NUMBER,
P_SUP_NAME VARCHAR2,P_FRACTION VARCHAR2)
AS 
LN_INV_ID INVENTORY_DTLS.INV_ID%TYPE;
LN_AVAL_AMNT INVENTORY_DTLS.AVAL_AMNT%TYPE;
LD_OFFER_DATE INVENTORY_DTLS.OFFER_DATE%TYPE;
LV_FRACTION INVENTORY_DTLS.FRACTION%TYPE;
LN_SUP_ID INVENTORY_DTLS.SUP_ID%TYPE;
LN_ASSET_AMNT INVENTORY_DTLS.ASSET_AMNT%TYPE;
LN_SPLIT_PER NUMBER;
BEGIN
  SELECT ID.INV_ID,NVL(ID.AVAL_AMNT,ID.ASSET_AMNT),ID.OFFER_DATE,ID.FRACTION,ID.SUP_ID,ID.ASSET_AMNT INTO 
  LN_INV_ID,LN_AVAL_AMNT,LD_OFFER_DATE,LV_FRACTION,LN_SUP_ID,LN_ASSET_AMNT
   FROM INVENTORY_DTLS ID WHERE ID.INV_ID = P_INV_ID;
   LN_SPLIT_PER :=(LN_ASSET_AMNT * P_SPLIT_PER)/100;
   
   IF  LN_SPLIT_PER > LN_AVAL_AMNT OR LV_FRACTION ='N' THEN
     RAISE_APPLICATION_ERROR (-20300,'THERE IS NO CHANCE TO SPLIT');
     END IF;
     
   END;
/
