CREATE OR REPLACE TRIGGER TRG_INV_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON INVENTORY_DTLS
FOR EACH ROW
  DECLARE 
  LN_INV_ID NUMBER;
  LV_ACTION VARCHAR2(40);
  BEGIN
    LN_INV_ID:= CASE WHEN :NEW.INV_ID IS NULL THEN 
    :OLD.INV_ID ELSE :NEW.INV_ID END;
    IF DELETING THEN
      DELETE FROM INVENTORY_DTLS ID WHERE ID.INV_ID = :OLD.INV_ID;
      ELSIF UPDATING THEN
      IF    :NEW.ASSET_AMNT <> :OLD.ASSET_AMNT THEN
    LV_ACTION:= 'INVENTORY SPLIT';
    ELSIF NVL(:OLD.LOCK_AMNT,0) < :NEW.LOCK_AMNT THEN
    LV_ACTION:='LOAN SANCTIONED';
     ELSIF NVL(:OLD.LOCK_AMNT,0) > :NEW.LOCK_AMNT THEN
    LV_ACTION:= 'LOAN CANCELLED';
     ELSE 
      LV_ACTION:= 'MODIFIER' ;
    END IF;
    END IF;
    IF INSERTING THEN
      LV_ACTION:='NEW INVENTORY';
      END IF;
    INSERT INTO AUDIT_INV_DTLS (inv_id, 
old_asset, 
new_asset, 
old_aval, 
new_aval, 
old_lock, 
new_lock, 
comd_id, 
action_date, 
action_type, 
status
)VALUES (LN_INV_ID,:OLD.ASSET_AMNT,:NEW.ASSET_AMNT,:OLD.AVAL_AMNT,:NEW.AVAL_AMNT,:OLD.LOCK_AMNT,:NEW.LOCK_AMNT,NVL(:NEW.COMD_ID,:OLD.COMD_ID),
SYSDATE,LV_ACTION,:OLD.STATUS);
END;
/
